pipeline:
  install:
    image: iknpx/archnode
    commands:
      - yarn
    when:
      branch:
        include: [ master, feature/* ]
      event:
        - push
        - pull_request

  lint:
    image: iknpx/archnode
    commands:
      - yarn lint
    when:
      branch:
        include: [ master, feature/* ]
      event:
        - push
        - pull_request

  build/ui:
    image: iknpx/archnode
    environment:
      - NODE_ENV=production
    commands:
      - yarn dist
    when:
      branch:
        include: [ master, feature/* ]
      event:
        - push
        - pull_request

  deploy:
    image: iknpx/archnode
    secrets: [ SSH_KEY, SSH_HOST, SSH_PATH ]
    commands:
      - yarn gulp deploy:production
    when:
      branch:
        include: [ master ]
      event:
        - push
